<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;

class CustomVerifyEmailController extends Controller
{
    /**
     * Verify a user's email address from the signed email link.
     */
    public function __invoke(Request $request, $id, $hash)
    {
        /*
        |--------------------------------------------------------------------------
        | Check signed URL
        |--------------------------------------------------------------------------
        |
        | The verification link must be generated by our application.
        |
        */

        if (! $request->hasValidSignature()) {
            abort(403, 'This verification link is invalid or has expired.');
        }

        /*
        |--------------------------------------------------------------------------
        | Find User
        |--------------------------------------------------------------------------
        */

        $user = User::findOrFail($id);

        /*
        |--------------------------------------------------------------------------
        | Check Email Hash
        |--------------------------------------------------------------------------
        */

        if (! hash_equals(
            $hash,
            sha1($user->getEmailForVerification())
        )) {
            abort(403, 'This verification link is invalid.');
        }

        /*
        |--------------------------------------------------------------------------
        | Already Verified
        |--------------------------------------------------------------------------
        */

        if ($user->hasVerifiedEmail()) {
            return redirect()
                ->route('login')
                ->with(
                    'status',
                    'Your email address is already verified. You can now log in.'
                );
        }

        /*
        |--------------------------------------------------------------------------
        | Mark Email As Verified
        |--------------------------------------------------------------------------
        */

        if ($user->markEmailAsVerified()) {
            event(new \Illuminate\Auth\Events\Verified($user));
        }

        /*
        |--------------------------------------------------------------------------
        | Redirect To Login
        |--------------------------------------------------------------------------
        */

        return redirect()
            ->route('login')
            ->with(
                'status',
                'Your email has been successfully verified. You can now log in.'
            );
    }
}
